-- Deterministic reference data only. User data is intentionally never seeded.
insert into public.countries (iso2,name,phone_code) values ('IN','India','+91'),('PK','Pakistan','+92'),('BD','Bangladesh','+880'),('AE','United Arab Emirates','+971'),('SA','Saudi Arabia','+966'),('GB','United Kingdom','+44'),('US','United States','+1'),('CA','Canada','+1'),('AU','Australia','+61') on conflict (iso2) do update set name=excluded.name, phone_code=excluded.phone_code;
insert into public.states(country_id,code,name) select c.id,v.code,v.name from public.countries c cross join (values ('MH','Maharashtra'),('DL','Delhi'),('KA','Karnataka'),('TG','Telangana'),('TN','Tamil Nadu'),('GJ','Gujarat'),('UP','Uttar Pradesh'),('WB','West Bengal'),('KL','Kerala'),('RJ','Rajasthan')) v(code,name) where c.iso2='IN' on conflict(country_id,code) do update set name=excluded.name;
insert into public.cities(state_id,name,latitude,longitude) select s.id,v.name,v.lat,v.lng from public.states s join public.countries c on c.id=s.country_id join (values ('MH','Mumbai',19.0760,72.8777),('MH','Pune',18.5204,73.8567),('DL','New Delhi',28.6139,77.2090),('KA','Bengaluru',12.9716,77.5946),('TG','Hyderabad',17.3850,78.4867),('TN','Chennai',13.0827,80.2707),('GJ','Ahmedabad',23.0225,72.5714),('UP','Lucknow',26.8467,80.9462),('WB','Kolkata',22.5726,88.3639),('KL','Kochi',9.9312,76.2673),('RJ','Jaipur',26.9124,75.7873)) v(state_code,name,lat,lng) on s.code=v.state_code where c.iso2='IN' on conflict(state_id,name) do nothing;
insert into public.lookup_values(category,code,label,sort_order) values
('relationship_status','single','Single',1),('relationship_status','separated','Separated',2),('relationship_status','divorced','Divorced',3),('relationship_status','widowed','Widowed',4),
('education_level','high_school','High school',1),('education_level','diploma','Diploma',2),('education_level','bachelors','Bachelor’s degree',3),('education_level','masters','Master’s degree',4),('education_level','doctorate','Doctorate',5),('education_level','religious','Islamic studies',6),
('occupation','technology','Technology',1),('occupation','healthcare','Healthcare',2),('occupation','education','Education',3),('occupation','finance','Finance',4),('occupation','business','Business',5),('occupation','government','Government',6),('occupation','homemaker','Homemaker',7),('occupation','student','Student',8),('occupation','other','Other',99),
('marital_status','never_married','Never married',1),('marital_status','divorced','Divorced',2),('marital_status','widowed','Widowed',3),
('language','english','English',1),('language','urdu','Urdu',2),('language','hindi','Hindi',3),('language','arabic','Arabic',4),('language','bengali','Bengali',5),('language','punjabi','Punjabi',6),('language','tamil','Tamil',7),('language','malayalam','Malayalam',8),
('religion','islam','Islam',1),('sect','sunni','Sunni',1),('sect','shia','Shia',2),('sect','ibadi','Ibadi',3),('sect','other','Other / prefer not to say',99)
on conflict(category,code) do update set label=excluded.label,sort_order=excluded.sort_order;
insert into public.subscription_plans(code,name,price_minor,currency,interval_months,features) values ('free','Free',0,'INR',1,'{"interests_per_month":20,"advanced_search":false}'::jsonb),('premium_monthly','Premium Monthly',99900,'INR',1,'{"unlimited_interests":true,"advanced_search":true,"read_receipts":true}'::jsonb),('premium_quarterly','Premium Quarterly',249900,'INR',3,'{"unlimited_interests":true,"advanced_search":true,"read_receipts":true}'::jsonb) on conflict(code) do update set name=excluded.name,price_minor=excluded.price_minor,features=excluded.features;
