create table public.countries (id uuid primary key default extensions.gen_random_uuid(), iso2 char(2) not null unique, name text not null unique, phone_code text, created_at timestamptz not null default now());
create table public.states (id uuid primary key default extensions.gen_random_uuid(), country_id uuid not null references public.countries(id) on delete restrict, code text not null, name text not null, unique(country_id, code));
create table public.cities (id uuid primary key default extensions.gen_random_uuid(), state_id uuid not null references public.states(id) on delete restrict, name text not null, latitude numeric(9,6), longitude numeric(9,6), unique(state_id, name));
create table public.lookup_values (id uuid primary key default extensions.gen_random_uuid(), category text not null check (category in ('relationship_status','education_level','occupation','marital_status','language','religion','sect')), code text not null, label text not null, sort_order smallint not null default 0, is_active boolean not null default true, unique(category, code));

create table public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  role public.account_role not null default 'user', email citext, display_name text not null check (char_length(display_name) between 2 and 80), gender public.gender not null, date_of_birth date not null check (date_of_birth <= current_date - interval '18 years' and date_of_birth >= current_date - interval '100 years'),
  bio text check (char_length(bio) <= 2000), city_id uuid references public.cities(id) on delete set null, marital_status_id uuid references public.lookup_values(id) on delete set null, religion_id uuid references public.lookup_values(id) on delete set null, sect_id uuid references public.lookup_values(id) on delete set null, prayer_frequency public.prayer_frequency, visibility public.profile_visibility not null default 'members_only', is_discoverable boolean not null default true, is_completed boolean not null default false, last_seen_at timestamptz, deleted_at timestamptz, created_at timestamptz not null default now(), updated_at timestamptz not null default now()
);
create table public.profile_photos (id uuid primary key default extensions.gen_random_uuid(), profile_id uuid not null references public.profiles(id) on delete cascade, storage_path text not null unique check (storage_path ~ '^[0-9a-f-]{36}/[0-9a-f-]{36}\.(jpg|jpeg|png|webp)$'), position smallint not null check (position between 0 and 9), is_primary boolean not null default false, moderation_status public.verification_status not null default 'pending', created_at timestamptz not null default now(), unique(profile_id, position));
create unique index profile_photos_one_primary on public.profile_photos(profile_id) where is_primary and moderation_status = 'approved';
create table public.profile_preferences (profile_id uuid primary key references public.profiles(id) on delete cascade, seeking_genders public.gender[] not null default '{}', min_age smallint check (min_age between 18 and 100), max_age smallint check (max_age between 18 and 100 and max_age >= min_age), city_ids uuid[] not null default '{}', religion_ids uuid[] not null default '{}', sect_ids uuid[] not null default '{}', education_ids uuid[] not null default '{}', updated_at timestamptz not null default now());
create table public.education (id uuid primary key default extensions.gen_random_uuid(), profile_id uuid not null references public.profiles(id) on delete cascade, level_id uuid references public.lookup_values(id) on delete set null, institution text, field_of_study text, graduation_year smallint check (graduation_year between 1950 and 2100), is_primary boolean not null default false, created_at timestamptz not null default now());
create table public.occupations (id uuid primary key default extensions.gen_random_uuid(), profile_id uuid not null references public.profiles(id) on delete cascade, occupation_id uuid references public.lookup_values(id) on delete set null, employer text, title text, annual_income_min integer check (annual_income_min >= 0), annual_income_max integer check (annual_income_max >= annual_income_min), currency char(3) not null default 'INR', is_primary boolean not null default false, created_at timestamptz not null default now());
create table public.family_information (profile_id uuid primary key references public.profiles(id) on delete cascade, father_occupation text, mother_occupation text, siblings_count smallint check (siblings_count between 0 and 30), family_location text, family_values text check (char_length(family_values) <= 1000), updated_at timestamptz not null default now());
create table public.profile_languages (profile_id uuid not null references public.profiles(id) on delete cascade, language_id uuid not null references public.lookup_values(id) on delete cascade, proficiency smallint not null default 3 check (proficiency between 1 and 5), primary key(profile_id, language_id));
create table public.user_verifications (id uuid primary key default extensions.gen_random_uuid(), profile_id uuid not null references public.profiles(id) on delete cascade, verification_type text not null check (verification_type in ('email','phone','identity','selfie','education')), status public.verification_status not null default 'pending', document_path text unique, reviewed_by uuid references public.profiles(id) on delete set null, reviewed_at timestamptz, rejection_reason text, expires_at timestamptz, created_at timestamptz not null default now(), updated_at timestamptz not null default now(), unique(profile_id, verification_type));

create index profiles_discovery_idx on public.profiles(gender, city_id, date_of_birth) where deleted_at is null and is_discoverable;
create index profiles_search_idx on public.profiles using gin (to_tsvector('simple', coalesce(display_name,'') || ' ' || coalesce(bio,'')));
create index profiles_name_trgm_idx on public.profiles using gin (display_name gin_trgm_ops);
create index profile_photos_profile_idx on public.profile_photos(profile_id, position);
create index cities_state_name_idx on public.cities(state_id, name);
create trigger profiles_updated_at before update on public.profiles for each row execute function public.set_updated_at();
create trigger preferences_updated_at before update on public.profile_preferences for each row execute function public.set_updated_at();
create trigger verifications_updated_at before update on public.user_verifications for each row execute function public.set_updated_at();
